name: Build PR
on: pull_request
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn --frozen-lockfile --ignore-scripts
      - name: Lint
        run: yarn prettier --check "./**/*.{js,md}"
